ssl_certificate /etc/nginx/ssl/voloian.cn_nginx/voloian.cn_bundle.crt;
ssl_certificate_key /etc/nginx/ssl/voloian.cn_nginx/voloian.cn.key;
ssl_session_cache shared:VLOIANSSL:10m;
ssl_session_timeout 10m;
ssl_session_tickets off;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;
