/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/app-bar/app-bar.vue')['default']
    BackCapsule: typeof import('./src/components/back-capsule/back-capsule.vue')['default']
    ChatComposer: typeof import('./src/components/chat-composer/chat-composer.vue')['default']
    ChatImportFeaturePoster: typeof import('./src/components/chat-import-feature-poster/chat-import-feature-poster.vue')['default']
    ChatMessageBubble: typeof import('./src/components/chat-message-bubble/chat-message-bubble.vue')['default']
    ChatMorePanel: typeof import('./src/components/chat-more-panel/chat-more-panel.vue')['default']
    ContactCoverBanner: typeof import('./src/components/contact-cover-banner/contact-cover-banner.vue')['default']
    CopyableText: typeof import('./src/components/copyable-text/copyable-text.vue')['default']
    EmojiPickerPanel: typeof import('./src/components/emoji-picker-panel/emoji-picker-panel.vue')['default']
    LoginPromptPopup: typeof import('./src/components/login-prompt-popup/login-prompt-popup.vue')['default']
    MomentCard: typeof import('./src/components/moment-card/moment-card.vue')['default']
    MomentsTicker: typeof import('./src/components/moments-ticker/moments-ticker.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRange: typeof import('@nutui/nutui-taro')['Range']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    PageScaffold: typeof import('./src/components/page-scaffold/page-scaffold.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopPromoBanner: typeof import('./src/components/top-promo-banner/top-promo-banner.vue')['default']
    VoiceCustomerServiceCard: typeof import('./src/components/voice-customer-service-card/voice-customer-service-card.vue')['default']
    VoicePackagePaymentPanel: typeof import('./src/components/voice-package-payment-panel/voice-package-payment-panel.vue')['default']
    VoicePackageSheet: typeof import('./src/components/voice-package-sheet/voice-package-sheet.vue')['default']
  }
}
