/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/app-bar/app-bar.vue')['default']
    BackCapsule: typeof import('./src/components/back-capsule/back-capsule.vue')['default']
    EmojiPickerPanel: typeof import('./src/components/emoji-picker-panel/emoji-picker-panel.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    PageScaffold: typeof import('./src/components/page-scaffold/page-scaffold.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
