server {
  listen 80;
  server_name admin.tianzhiling.chat;

  resolver 127.0.0.11 ipv6=off valid=30s;
  set $tzl_admin_node_backend http://tzl_admin_node:7101;

  client_max_body_size 50m;

  include /etc/nginx/includes/health.conf;

  location / {
    proxy_pass $tzl_admin_node_backend;
    include /etc/nginx/includes/proxy-headers.conf;
    include /etc/nginx/includes/proxy-timeouts.conf;
    proxy_buffering off;
  }
}
