server {
  listen 80;
  server_name admin.voloian.cn;

  include /etc/nginx/includes/health.conf;

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  server_name admin.voloian.cn;

  resolver 127.0.0.11 ipv6=off valid=30s;
  set $tzl_admin_web_backend http://tzl_admin_web:80;
  set $tzl_admin_node_backend http://tzl_admin_node:7101;

  include /etc/nginx/includes/ssl-admin-tianzhiling-chat.conf;

  client_max_body_size 50m;

  include /etc/nginx/includes/health.conf;

  location /admin_api/ {
    proxy_pass $tzl_admin_node_backend;
    include /etc/nginx/includes/proxy-headers.conf;
    include /etc/nginx/includes/proxy-timeouts.conf;
    proxy_buffering off;
  }

  location / {
    proxy_pass $tzl_admin_web_backend;
    include /etc/nginx/includes/proxy-headers.conf;
    include /etc/nginx/includes/proxy-timeouts.conf;
  }
}
